name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - notebook=6.5.4
  - seaborn=0.12.2
  - pandas=2.0.3
  - pyarrow=11.0.0
  - pip=23.2.1
  - ydata-profiling
  - ipywidgets
  - pip:
      - wandb==0.15.12
      - matplotlib==3.7.2