name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - mlflow=2.6.0
  - ipython=8.15.0
  - notebook=6.5.4
  - hydra-core=1.2.0
  - pandas=2.0.3
  - git=2.40.1
  - pip=23.2.1
  - pip:
      - wandb==0.15.12
      - matplotlib==3.7.2
