name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pandas=2.0.3
  - pip=23.2.1
  - mlflow=2.6.0
  - scikit-learn=1.3.0
  - pillow=9.4.0
  - pip:
      - wandb==0.15.12
      - matplotlib==3.7.2
